### ISSUE TITLE
feat: Fine-grained configuration for benchmarking server via Python client

### ISSUE THREAD

**Issue by antferdom** [huggingface/text-generation-inference#1133]
### Feature request

A concise Python script for fast experimentation of the inference server using the Python client, and with a formal configuration file. This utility script can also serve as a straightforward approach for interacting with the client, thus being a generic example.

### Motivation

Although there is already a benchmarking utility, it exists in the Rust domain, thus decreasing prototyping speed for several users. Therefore the creation of a similar utility within Python ecosystem, which can also leverage configuration modules for complex applications like [Meta Hydra](https://github.com/facebookresearch/hydra).

### Your contribution

A Python benchmarking utility for the inference server using the Python client. The experiments are handled using Hydra & Omegaconf with an yaml config file. See the following configuration file example:
```yaml
deployment:
  addr: http://127.0.0.1
  port: 8080
  max_concurrent_requests: 64
  local: True
  endpoint: ""

macros:
  tokenizer_name: bigscience/bloom-560m

GenerationConfig:
  max_new_tokens: 100
  repetition_penalty: 1.5
  do_sample: True
  stop_sequences: 
    - "length"
  sequence_length: 100
```

_example result_
```bash
Serving elapsed time: 7.8493 seconds
Total requests: 64
Total sequences tokens: 6400
Sequence length: 100
Total decoded tokens: 5886
Throughput: 749.8712100018795 tokens/sec
Total processed tokens: 12286
```
