### ISSUE TITLE
HuggingFaceH4/zephyr-7b-beta  issue "Method prefill encountered error"

### ISSUE THREAD

**Issue by muhammad-asn** [huggingface/text-generation-inference#1566]
### System Info

Text-generation-inference: v1.1.0
OS: Ubuntu 22.04.3
Nvidia driver: 545.23.08
CUDA version: 12.3
Chat UI: [https://github.com/huggingface/chat-ui/ tag v.0.7](https://github.com/huggingface/chat-ui/tree/v0.7)
GPU: A100 80GB

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Deploy TGI with this config
```yaml
services:
  llm:
    image: ghcr.io/huggingface/text-generation-inference:1.1.0
    container_name: llm
    command: >
      --model-id HuggingFaceH4/zephyr-7b-beta 
      --max-total-tokens 8192 
      --max-input-length 4096 
      --num-shard 1 
      --max-top-n-tokens 1 
      --max-best-of 1 
      --disable-custom-kernels 
      --trust-remote-code  
      --max-stop-sequences 1  
      --validation-workers 1 
      --waiting-served-ratio 0 
      --max-batch-total-tokens 8192 
      --max-batch-prefill-tokens 4096 
      --max-waiting-tokens 4096 
      --cuda-memory-fraction 0.8
      --max-concurrent-requests 512
    volumes:
      - ./data:/data
    ports:
      - 8080:80
    shm_size: '1gb'
    restart: always
    environment:
      - CUDA_LAUNCH_BLOCKING=1
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
```
2. Deploy Chat UI with this config (`.env.local`)
```ini
MONGODB_URL=mongodb://mongodb:27017
MONGODB_DB_NAME=chat-ui
MONGODB_DIRECT_CONNECTION=false

MODELS=`[
    {
      "name": "HuggingFaceH4/zephyr-7b-beta",
      "displayName": "HuggingFaceH4/zephyr-7b-beta",
      "description": "Zephyr 7b Beta Model",
      "websiteUrl": "https://huggingface.co/HuggingFaceH4/zephyr-7b-beta",
      "preprompt": "",
      "parameters": {
        "details": false,
        "do_sample": true,
        "max_new_tokens": 4096,
        "best_of": 1,
        "repetition_penalty": 1.17,
        "return_full_text": false,
        "temperature": 0.01,
        "top_p": 0.14,
        "top_k": 49,
        "truncate": 4096,
        "typical_p": 0.99,
        "watermark": false,
        "decoder_input_details": false
      },
      "endpoints": [{
        "type" : "tgi",
        "url": "http://llm/generate_stream"
      }],
      "promptExamples": [
        {
          "title": "Write an email from bullet list",
          "prompt": "As a restaurant owner, write a professional email to the supplier to get these products every week: \n\n- Wine (x10)\n- Eggs (x24)\n- Bread (x12)"
        }, {
          "title": "Code a snake game",
          "prompt": "Code a basic snake game in python, give explanations for each step."
        }, {
          "title": "Assist in a task",
          "prompt": "How do I make a delicious lemon cheesecake?"
        }
      ]
    }
]`

## THIS LINE BELOW IS MANDATORY FOR DEFAULT VALUE ##
OLD_MODELS=`[]`# any removed models, `{ name: string, displayName?: string, id?: string }`
TASK_MODEL= # name of the model used for tasks such as summarizing title, creating query, etc.

PUBLIC_ORIGIN=#https://huggingface.co
PUBLIC_SHARE_PREFIX=#https://hf.co/chat
PUBLIC_GOOGLE_ANALYTICS_ID=#G-XXXXXXXX / Leave empty to disable
PUBLIC_ANNOUNCEMENT_BANNERS=`[
    {
    "title": "Llama v2 is live on HuggingChat! 🦙",
    "linkTitle": "Announcement",
    "linkHref": "https://huggingface.co/blog/llama2"
  }
]`

PARQUET_EXPORT_DATASET=
PARQUET_EXPORT_HF_TOKEN=
PARQUET_EXPORT_SECRET=

RATE_LIMIT= # requests per minute
MESSAGES_BEFORE_LOGIN=# how many messages a user can send in a conversation before having to login. set to 0 to force login right away

PUBLIC_APP_NAME=ChatUI # name used as title throughout the app
PUBLIC_APP_ASSETS=chatui # used to find logos & favicons in static/$PUBLIC_APP_ASSETS
PUBLIC_APP_COLOR=blue # can be any of tailwind colors: https://tailwindcss.com/docs/customizing-colors#default-color-palette
PUBLIC_APP_DESCRIPTION=# description used throughout the app (if not set, a default one will be used)
PUBLIC_APP_DATA_SHARING=#set to 1 to enable options & text regarding data sharing
PUBLIC_APP_DISCLAIMER=#set to 1 to show a disclaimer on login page
LLM_SUMMERIZATION=true


COOKIE_NAME=hf-chat
HF_TOKEN=#hf_<token> from from https://huggingface.co/settings/token
HF_API_ROOT=https://api-inference.huggingface.co/models
OPENAI_API_KEY=#your openai api key here

HF_ACCESS_TOKEN=#LEGACY! Use HF_TOKEN instead

# used to activate search with web functionality. disabled if none are defined. choose one of the following:
YDC_API_KEY=#your docs.you.com api key here
SERPER_API_KEY=#your serper.dev api key here
SERPAPI_KEY=#your serpapi key here
SERPSTACK_API_KEY=#your serpstack api key here
USE_LOCAL_WEBSEARCH=#set to true to parse google results yourself, overrides other API keys

WEBSEARCH_ALLOWLIST=`[]` # if it's defined, allow websites from only this list.
WEBSEARCH_BLOCKLIST=`[]` # if it's defined, block websites from this list.

# Parameters to enable open id login
OPENID_CONFIG=`{
  "PROVIDER_URL": "",
  "CLIENT_ID": "",
  "CLIENT_SECRET": "",
  "SCOPES": ""
}`

# /!\ legacy openid settings, prefer the config above
OPENID_CLIENT_ID=
OPENID_CLIENT_SECRET=
OPENID_SCOPES="openid profile" # Add "email" for some providers like Google that do not provide preferred_username
OPENID_PROVIDER_URL=https://huggingface.co # for Google, use https://accounts.google.com
OPENID_TOLERANCE=
OPENID_RESOURCE=

# Parameters to enable a global mTLS context for client fetch requests
USE_CLIENT_CERTIFICATE=false
CERT_PATH=#
KEY_PATH=#
CA_PATH=#
CLIENT_KEY_PASSWORD=#
REJECT_UNAUTHORIZED=true
```

3. Run multiple concurrent requests, after a while it shows an error
```
Remove prefill token due to error

2024-02-16T06:37:34.615391Z ERROR health:prefill{id=18446744073709551615 size=1}:prefill{id=18446744073709551615 size=1}: text_generation_client: router/client/src/lib.rs:33: Server error: Unexpected <class 'RuntimeError'>: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2024-02-16T06:37:52.693170Z ERROR text_generation_launcher: Method Prefill encountered an error.
```

### Expected behavior

The TGI should be run seamlessly and without issue.

**Comment by muhammad-asn** [comment]
@OlivierDehaene @Narsil

**Comment by muhammad-asn** [comment]
Any update?

**Comment by OlivierDehaene** [comment]
If you could try with the latest version that would be great! 1.4.2

**Comment by muhammad-asn** [comment]
@OlivierDehaene can you assist which line that cause the bug or issue?

**Comment by OlivierDehaene** [comment]
```yaml
services:
  llm:
    image: ghcr.io/huggingface/text-generation-inference:1.4.2
    container_name: llm
    command: >
      --model-id HuggingFaceH4/zephyr-7b-beta 
      --max-total-tokens 8192 
      --max-input-length 4096 
      --num-shard 1 
      --max-top-n-tokens 1 
      --max-best-of 1 
      --disable-custom-kernels 
      --trust-remote-code  
      --max-stop-sequences 1  
      --validation-workers 1 
      --waiting-served-ratio 0 
      --max-batch-total-tokens 8192 
      --max-batch-prefill-tokens 4096 
      --max-waiting-tokens 4096 
      --cuda-memory-fraction 0.8
      --max-concurrent-requests 512
    volumes:
      - ./data:/data
    ports:
      - 8080:80
    shm_size: '1gb'
    restart: always
    environment:
      - CUDA_LAUNCH_BLOCKING=1
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
```
