### ISSUE TITLE
TGI cannot run properly on GKE

### ISSUE THREAD

**Issue by oOraph** [huggingface/text-generation-inference#1711]
### System Info

tgi v1.4.5

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

run this pod on gke

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test-tgi
  name: test-tgi
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - "infinity"
    image: ghcr.io/huggingface/text-generation-inference:1.4.5
    imagePullPolicy: IfNotPresent
    name: nvidia
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
        nvidia.com/gpu: "1"
      requests:
        cpu: "1"
        memory: 2Gi
        nvidia.com/gpu: "1"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
```

Run

```
text-generation-launcher --model-id TheBloke/OpenHermes-2.5-Mistral-7B-GPTQ --quantize gptq
```

Error:

tgi server complains about a missing libcuda.so file missing.

Even when the LD_LIBRARY_PATH is properly configured for the tgi server and includes the directory that contains the said file

The reason is that the lib is indeed here but in some environments the ld cache is not up to date

This happens on GKE that expose gpus but for some reason does not use the nvidia-container-runtime. To expose gpu devices properly they also need to share some dynamic libs from the host to the container (to avoid cuda/nvidia lib versions conflict as much as possible, just like nvidia-ctk does): apparently they do not run ldconfig as a precommand during the ocr setup. This is mandatory though

What's worse is that as soon as you execute any intermediate action that triggers a ld.so.cache refresh (apt-get install whateverpackagewithsharedlibslikevim for example) then the command above will properly work (easy to understand once the solution is here, drives you nuts when you're trying to understand the issue and you observe this ><)

Here some obscur gptq lib was complaining and Triton. What is weird is that they should have searched for .so files from LD_LIBRARY_PATH before looking into ld.so.cache (here the env var seems just ignored)

The proposed solution is a generic fix, often useless, always harmless, and does not cost much time 

### Expected behavior

tgi works on gke
