### ISSUE TITLE
Could not import SGMV kernel from Punica

### ISSUE THREAD

**Issue by freegheist** [huggingface/text-generation-inference#2188]
### System Info

Docker v2.1.1
Ubuntu 22.04, 8xA6000 Ampere
Nvidia Driver: v555.42.02 / CUDA Version: 12.5

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Args {
    model_id: "meta-llama/Meta-Llama-3-8B-Instruct",
    revision: None,
    validation_workers: 15,
    sharded: None,
    num_shard: Some(
        8,
    ),
    quantize: Some(
        Eetq,
    ),
    speculate: None,
    dtype: None,
    trust_remote_code: false,
    max_concurrent_requests: 128,
    max_best_of: 2,
    max_stop_sequences: 4,
    max_top_n_tokens: 5,
    max_input_tokens: None,
    max_input_length: Some(
        6144,
    ),
    max_total_tokens: Some(
        8192,
    ),
    waiting_served_ratio: 0.3,
    max_batch_prefill_tokens: Some(
        6144,
    ),
    max_batch_total_tokens: Some(
        8192,
    ),
    max_waiting_tokens: 20,
    max_batch_size: None,
    cuda_graphs: Some(
        [
            1,
            2,
            4,
            8,
            16,
            32,
        ],
    ),
    hostname: "0.0.0.0",
    port: 80,
    shard_uds_path: "/tmp/text-generation-server",
    master_addr: "localhost",
    master_port: 29500,
    huggingface_hub_cache: Some(
        "/data",
    ),
    weights_cache_override: None,
    disable_custom_kernels: false,
    cuda_memory_fraction: 0.99,
    rope_scaling: None,
    rope_factor: None,
    json_output: false,
    otlp_endpoint: None,
    otlp_service_name: "text-generation-inference.router",
    cors_allow_origin: [],
    watermark_gamma: None,
    watermark_delta: None,
    ngrok: false,
    ngrok_authtoken: None,
    ngrok_edge: None,
    tokenizer_config_path: None,
    disable_grammar_support: false,
    env: false,
    max_client_batch_size: 4,
    lora_adapters: None,
}

### Expected behavior

2024-07-04T23:00:48.811577Z  INFO shard-manager: text_generation_launcher: Starting shard rank=4
2024-07-04T23:00:48.811542Z  INFO shard-manager: text_generation_launcher: Starting shard rank=2
2024-07-04T23:00:48.811928Z  INFO shard-manager: text_generation_launcher: Starting shard rank=6
2024-07-04T23:00:48.812027Z  INFO shard-manager: text_generation_launcher: Starting shard rank=5
2024-07-04T23:00:48.812029Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2024-07-04T23:00:48.811781Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2024-07-04T23:00:48.812052Z  INFO shard-manager: text_generation_launcher: Starting shard rank=7
2024-07-04T23:00:48.812076Z  INFO shard-manager: text_generation_launcher: Starting shard rank=3
2024-07-04T23:00:50.158244Z  INFO text_generation_launcher: Detected system rocm
2024-07-04T23:00:50.206696Z  INFO text_generation_launcher: Detected system rocm
2024-07-04T23:00:50.206697Z  INFO text_generation_launcher: Detected system rocm
2024-07-04T23:00:50.206695Z  INFO text_generation_launcher: Detected system rocm
2024-07-04T23:00:50.207263Z  INFO text_generation_launcher: Detected system rocm
2024-07-04T23:00:50.207912Z  INFO text_generation_launcher: Detected system rocm
2024-07-04T23:00:50.209409Z  INFO text_generation_launcher: Detected system rocm
2024-07-04T23:00:50.211183Z  INFO text_generation_launcher: Detected system rocm
2024-07-04T23:00:52.317809Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/sgmv.py:18: UserWarning: Could not import SGMV kernel from Punica, falling back to loop.
  warnings.warn("Could not import SGMV kernel from Punica, falling back to loop.")
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 75, in serve
    from text_generation_server import server

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 14, in <module>
    from text_generation_server.cache import Cache

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cache.py", line 5, in <module>
    from text_generation_server.models.types import Batch

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 55, in <module>
    from text_generation_server.models.flash_causal_lm import FlashCausalLM

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 39, in <module>
    from text_generation_server.layers.attention import Seqlen

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/layers/attention/__init__.py", line 11, in <module>
    from .rocm import attention, paged_attention, reshape_and_cache, SUPPORTS_WINDOWING

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/layers/attention/rocm.py", line 8, in <module>
    major, minor = torch.cuda.get_device_capability()

  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 430, in get_device_capability
    prop = get_device_properties(device)

  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 444, in get_device_properties
    _lazy_init()  # will define _get_device_properties

  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()

RuntimeError: No HIP GPUs are available
 rank=1

...Tested Mixtral and LLama, same error since v2.1.1 (guessing it relates to the new LORA merges?)

**Comment by Hugoch** [comment]
TGI detects you system as being ROCM 
` 2024-07-04T23:00:50.158244Z INFO text_generation_launcher: Detected system rocm`
Any chance you have some AMD GPUs on the machine?

**Comment by freegheist** [comment]
> TGI detects you system as being ROCM ` 2024-07-04T23:00:50.158244Z INFO text_generation_launcher: Detected system rocm` Any chance you have some AMD GPUs on the machine?

no, full system is:

mobo: Pro WS WRX80E-SAGE SE WIFI II (FW: 1.32.0)
cpu: Threadripper Pro 5975WX
ram: 256 GB DDR4
gpu 8xA6000 Ampere 

6 GPUs are 16x on the PCI-E 4, the last slot is bifurcated to two 8x.  Just those 8 cards.

Everything works fine <= TGI v2.1.0.  But in 2.1.1 this ROCM error pops up

**Comment by freegheist** [comment]
> TGI detects you system as being ROCM ` 2024-07-04T23:00:50.158244Z INFO text_generation_launcher: Detected system rocm` Any chance you have some AMD GPUs on the machine?

...there is technically a 9th device, the onboard VGA on that ASUS mobo, this ASSPEED device:

```
lspci | grep -E 'VGA|3D|Display'
01:00.0 VGA compatible controller: NVIDIA Corporation GA102GL [RTX A6000] (rev a1)
02:00.0 VGA compatible controller: NVIDIA Corporation GA102GL [RTX A6000] (rev a1)
03:00.0 VGA compatible controller: NVIDIA Corporation GA102GL [RTX A6000] (rev a1)
29:00.0 VGA compatible controller: ASPEED Technology, Inc. ASPEED Graphics Family (rev 41)
2c:00.0 VGA compatible controller: NVIDIA Corporation GA102GL [RTX A6000] (rev a1)
41:00.0 VGA compatible controller: NVIDIA Corporation GA102GL [RTX A6000] (rev a1)
42:00.0 VGA compatible controller: NVIDIA Corporation GA102GL [RTX A6000] (rev a1)
61:00.0 VGA compatible controller: NVIDIA Corporation GA102GL [RTX A6000] (rev a1)
62:00.0 VGA compatible controller: NVIDIA Corporation GA102GL [RTX A6000] (rev a1)
```
Inxi:
```
inxi -Gxx
Graphics:
  Device-1: NVIDIA GA102GL [RTX A6000] driver: nvidia v: 555.42.02 pcie: speed: 5 GT/s lanes: 16
    ports: active: none empty: DP-21, DP-22, DP-23, DP-24 bus-ID: 01:00.0 chip-ID: 10de:2230
  Device-2: NVIDIA GA102GL [RTX A6000] driver: nvidia v: 555.42.02 pcie: speed: 5 GT/s lanes: 8
    ports: active: none empty: DP-25, DP-26, DP-27, DP-28 bus-ID: 02:00.0 chip-ID: 10de:2230
  Device-3: NVIDIA GA102GL [RTX A6000] driver: nvidia v: 555.42.02 pcie: speed: 2.5 GT/s
    lanes: 8 ports: active: none empty: DP-29, DP-30, DP-31, DP-32 bus-ID: 03:00.0
    chip-ID: 10de:2230
  Device-4: ASPEED Graphics Family driver: ast v: kernel ports: active: VGA-1 empty: none
    bus-ID: 29:00.0 chip-ID: 1a03:2000
  Device-5: NVIDIA GA102GL [RTX A6000] driver: nvidia v: 555.42.02 pcie: speed: 2.5 GT/s
    lanes: 16 ports: active: none empty: DP-17, DP-18, DP-19, DP-20 bus-ID: 2c:00.0
    chip-ID: 10de:2230
  Device-6: NVIDIA GA102GL [RTX A6000] driver: nvidia v: 555.42.02 pcie: speed: 2.5 GT/s
    lanes: 16 ports: active: none empty: DP-10, DP-11, DP-12, DP-9 bus-ID: 41:00.0
    chip-ID: 10de:2230
  Device-7: NVIDIA GA102GL [RTX A6000] driver: nvidia v: 555.42.02 pcie: speed: 2.5 GT/s
    lanes: 16 ports: active: none empty: DP-13, DP-14, DP-15, DP-16 bus-ID: 42:00.0
    chip-ID: 10de:2230
  Device-8: NVIDIA GA102GL [RTX A6000] driver: nvidia v: 555.42.02 pcie: speed: 2.5 GT/s
    lanes: 16 ports: active: none empty: DP-1, DP-2, DP-3, DP-4 bus-ID: 61:00.0 chip-ID: 10de:2230
  Device-9: NVIDIA GA102GL [RTX A6000] driver: nvidia v: 555.42.02 pcie: speed: 2.5 GT/s
    lanes: 16 ports: active: none empty: DP-5, DP-6, DP-7, DP-8 bus-ID: 62:00.0 chip-ID: 10de:2230
  Display: server: X.org v: 1.21.1.4 driver: gpu: ast note:  X driver n/a tty: 186x108
  Monitor-1: VGA-1 size-res: N/A in console
  Message: GL data unavailable in console. Try -G --display
```
HWInfo for the ASPEED device:
```
77: PCI 2900.0: 0300 VGA compatible controller (VGA)
  [Created at pci.386]
  Unique ID: W2eL.24StTwgmuV9
  Parent ID: rBRC._tiwZrVTbc2
  SysFS ID: /devices/pci0000:20/0000:20:01.1/0000:21:00.0/0000:22:06.0/0000:28:00.0/0000:29:00.0
  SysFS BusID: 0000:29:00.0
  Hardware Class: graphics card
  Model: "ASPEED AST1000/2000"
  Vendor: pci 0x1a03 "ASPEED Technology Inc."
  Device: pci 0x2000 "AST1000/2000"
  SubVendor: pci 0x1a03 "ASPEED Technology Inc."
  SubDevice: pci 0x2000 
  Revision: 0x41
  Driver: "ast"
  Driver Modules: "ast"
  Memory Range: 0xc0000000-0xc3ffffff (rw,non-prefetchable)
  Memory Range: 0xc4000000-0xc401ffff (rw,non-prefetchable)
  I/O Ports: 0x4000-0x7fff (rw)
  Memory Range: 0x000c0000-0x000dffff (rw,non-prefetchable,disabled)
  IRQ: 71 (no events)
  Module Alias: "pci:v00001A03d00002000sv00001A03sd00002000bc03sc00i00"
  Driver Info #0:
    XFree86 v4 Server Module: ast
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #93 (PCI bridge)
```
I also ran these commands to find any traces of ROCM but all came back null:
```
dpkg -l | grep rocm
printenv | grep -E 'ROC|HIP|AMD'
ls -l /usr/local/cuda/lib64/* | grep '\->.*rocm'
```
