### ISSUE TITLE
Can't run llama3.1-70b at full context

### ISSUE THREAD

**Issue by pseudotensor** [huggingface/text-generation-inference#2301]
### System Info

2.2.0

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

On 4*H100:
```
docker stop llama31-70b-tgi ; docker remove llama31-70b-tgi
sudo docker run -d --restart=always --gpus '"device=0,1,2,3"' \
             --shm-size 10.24gb \
             -e HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN \
             -e TRANSFORMERS_CACHE="/.cache/" -p \
             5005:80 \
             -v $HOME/.cache:/.cache/ \
             -v $HOME/.cache/huggingface/hub/:/data \
             --name llama31-70b-tgi \
             ghcr.io/huggingface/text-generation-inference:2.2.0 \
             --model-id meta-llama/Meta-Llama-3.1-70B-Instruct \
             --max-input-length 131072 \
             --max-total-tokens 139264 \
              --max-stop-sequences 6 \
              --num-shard 4 --sharded true &>> logs.llama3.1-70b.tgi.txt
```

get:

```
RuntimeError: Not enough memory to handle 131122 prefill tokens. You need to decrease `--max-batch-prefill-tokens`
```

vLLM works fine without errors.

### Expected behavior

able to launch and use without error like vLLM

**Comment by pseudotensor** [comment]
At least 65k works, but why doesn't 128k?

```
docker stop llama31-70b-tgi ; docker remove llama31-70b-tgi
source ~/h2ogpt_ops/gr_exports.sh
sudo docker run -d --restart=always --gpus '"device=0,1,2,3"' \
             --shm-size 10.24gb \
             -e HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN \
             -e TRANSFORMERS_CACHE="/.cache/" -p \
             5005:80 \
             -v $HOME/.cache:/.cache/ \
             -v $HOME/.cache/huggingface/hub/:/data \
             --name llama31-70b-tgi \
             ghcr.io/huggingface/text-generation-inference:2.2.0 \
             --model-id meta-llama/Meta-Llama-3.1-70B-Instruct \
             --max-input-length 66560 \
             --max-total-tokens 74752 \
              --max-stop-sequences 6 \
              --num-shard 4 --sharded true &>> logs.llama3.1-70b.tgi.txt
```

**Comment by pseudotensor** [comment]
Only 32k actually started:

```
docker stop llama31-70b-tgi ; docker remove llama31-70b-tgi
source ~/h2ogpt_ops/gr_exports.sh
sudo docker run -d --restart=always --gpus '"device=0,1,2,3"' \
             --shm-size 10.24gb \
             -e HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN \
             -e TRANSFORMERS_CACHE="/.cache/" -p \
             5005:80 \
             -v $HOME/.cache:/.cache/ \
             -v $HOME/.cache/huggingface/hub/:/data \
             --name llama31-70b-tgi \
             ghcr.io/huggingface/text-generation-inference:2.2.0 \
             --model-id meta-llama/Meta-Llama-3.1-70B-Instruct \
             --max-input-length 32768 \
             --max-total-tokens 40960 \
              --max-stop-sequences 6 \
              --num-shard 4 --sharded true &>> logs.llama3.1-70b.tgi.txt
```

**Comment by coderchem** [comment]
TGI does not support it now ,updates are so slow

**Comment by Jason-CKY** [comment]
Having the same issue. I run into OOM errors even when running llama 3.1 8b with 128k context on 2 80Gb A100. Feels like something in the prefill is taking up more VRAM

**Comment by freegheist** [comment]
> Having the same issue. I run into OOM errors even when running llama 3.1 8b with 128k context on 2 80Gb A100. Feels like something in the prefill is taking up more VRAM

KV Cache for the 8B at FP16 should be like 16GB plus the model so total 32GB VRAM you would need? 2x80GB A100 should easily handle that

**Comment by rishu931997** [comment]
Facing similar issue. I'm using 4xA100 80GB but it's throwing the same issue when trying to set context length more than 40k. Is there any fix for this?

**Comment by nrepesh** [comment]
Same issue. Commenting for visibility.

**Comment by mjsteele12** [comment]
same here for 3.1-70b. just adding that I'm using AWQ and can only run something like ~23k tokens on 2x a6000 ada (96 GB total VRAM), while using VLLM I can run the full 128k no issue.

**Comment by weihanfeng** [comment]
same issue on 4xA100 80gb

**Comment by maziyarpanahi** [comment]
I can't fit this model with 128K as well, something is not playing nice here. (tested the vLLM with 128K, no problem)

**Comment by badrisnps** [comment]
THe automatic inference of max-batch-prefill-tokens during the warmup phase is exceeding the VRAM. There seems to be no easy way to control the automatic estimation of that.

**Comment by localmind-ai** [comment]
Same issue on 4xA5000 (with Marlin FP8 quantization).

**Comment by ErikKaum** [comment]
Hi everyone 👋 

Sorry for such a late reply.
Thanks for reporting this issue and bringing it to our attention. We're currently rewriting a bunch of things and a fix for this is among those 👍 

It seems that vLLM forces a prefix chunk of 32k (which TGI doesn't) which causes the discrepancy.

**Comment by chuddlestonCBANC** [comment]
Any update on the timing around this?

**Comment by ErikKaum** [comment]
@chuddlestonCBANC it's in the works 🙌 
https://github.com/huggingface/text-generation-inference/pull/2402

**Comment by raimannma** [comment]
@ErikKaum After #2402 got merged, I still can't fit Llama 3.1 on my 4xA6000

The logs say that prefic caching is being used:
```
tgi-llama3.1-70b-1  | 2024-08-20T11:52:04.171854Z  INFO text_generation_launcher: Using prefix caching = True
tgi-llama3.1-70b-1  | 2024-08-20T11:52:04.171911Z  INFO text_generation_launcher: Using Attention = flashinfer
```

But even with only 16k input and 32k total tokens i get a CUDA out of Memory Error.
With vLLM i can get 80k tokens context length on the same server.

```
tgi-llama3.1-70b-1  | Traceback (most recent call last):
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 1251, in warmup
tgi-llama3.1-70b-1  |     _, batch, _ = self.generate_token(batch)
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
tgi-llama3.1-70b-1  |     return func(*args, **kwds)
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 1693, in generate_token
tgi-llama3.1-70b-1  |     prefill_logprobs_tensor = torch.log_softmax(out, -1)
tgi-llama3.1-70b-1  | torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.93 GiB. GPU 2 has a total capacity of 47.53 GiB of which 1.18 GiB is free. Process 790346 has 46.33 GiB memory in use. Of the allocated memory 45.87 GiB is allocated by PyTorch, and 30.45 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
tgi-llama3.1-70b-1  | 
tgi-llama3.1-70b-1  | The above exception was the direct cause of the following exception:
tgi-llama3.1-70b-1  | 
tgi-llama3.1-70b-1  | Traceback (most recent call last):
tgi-llama3.1-70b-1  |   File "/opt/conda/bin/text-generation-server", line 8, in <module>
tgi-llama3.1-70b-1  |     sys.exit(app())
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
tgi-llama3.1-70b-1  |     return get_command(self)(*args, **kwargs)
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
tgi-llama3.1-70b-1  |     return self.main(*args, **kwargs)
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
tgi-llama3.1-70b-1  |     return _main(
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
tgi-llama3.1-70b-1  |     rv = self.invoke(ctx)
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
tgi-llama3.1-70b-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
tgi-llama3.1-70b-1  |     return ctx.invoke(self.callback, **ctx.params)
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
tgi-llama3.1-70b-1  |     return __callback(*args, **kwargs)
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
tgi-llama3.1-70b-1  |     return callback(**use_params)  # type: ignore
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 109, in serve
tgi-llama3.1-70b-1  |     server.serve(
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 274, in serve
tgi-llama3.1-70b-1  |     asyncio.run(
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
tgi-llama3.1-70b-1  |     return loop.run_until_complete(main)
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
tgi-llama3.1-70b-1  |     self.run_forever()
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
tgi-llama3.1-70b-1  |     self._run_once()
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
tgi-llama3.1-70b-1  |     handle._run()
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
tgi-llama3.1-70b-1  |     self._context.run(self._callback, *self._args)
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/site-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method
tgi-llama3.1-70b-1  |     return await self.intercept(
tgi-llama3.1-70b-1  | > File "/opt/conda/lib/python3.10/site-packages/text_generation_server/interceptor.py", line 21, in intercept
tgi-llama3.1-70b-1  |     return await response
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 120, in _unary_interceptor
tgi-llama3.1-70b-1  |     raise error
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 111, in _unary_interceptor
tgi-llama3.1-70b-1  |     return await behavior(request_or_iterator, context)
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 123, in Warmup
tgi-llama3.1-70b-1  |     max_supported_total_tokens = self.model.warmup(batch)
tgi-llama3.1-70b-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 1253, in warmup
tgi-llama3.1-70b-1  |     raise RuntimeError(
tgi-llama3.1-70b-1  | RuntimeError: Not enough memory to handle 2 prefill tokens. You need to decrease `--max-batch-prefill-tokens`
```

This is my docker compose file:
```yaml
services:
  tgi-llama3.1-70b:
#    image: ghcr.io/huggingface/text-generation-inference
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    shm_size: 64g
    env_file: .env
    environment:
      TRUST_REMOTE_CODE: true
      MODEL_ID: meta-llama/Meta-Llama-3.1-70B-Instruct
      HUGGINGFACE_HUB_CACHE: /data
      MAX_TOTAL_TOKENS: 32768
      MAX_INPUT_TOKENS: 16384
      MAX_STOP_SEQUENCES: 5
      HOSTNAME: 0.0.0.0
      USAGE_STATS: off
      USE_PREFIX_CACHING: true
      FLASH_INFER: true
    volumes:
      - /data/huggingface/hub/:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [ gpu ]
```

And the docker file
```dockerfile
FROM ghcr.io/huggingface/text-generation-inference

RUN pip install --no-cache-dir flashinfer -i https://flashinfer.ai/whl/cu124/torch2.4

ENTRYPOINT ["/tgi-entrypoint.sh"]
```

**Comment by freegheist** [comment]
@ErikKaum any plans to look at the OOM issues with large contexts? I still get the OOM (mentioned above) regardless of prefix caching on the latest Docker images it seems.

**Comment by dacox** [comment]
@ErikKaum @freegheist Yeah, I was evaluating this and trying to do napkin math for gpu memory.

I am unable to run LLama3.1-8b even at 64k on an A100.

Not enough memory to handle 2 prefill tokens. from Meta seems to imply 128k should only take 16GB of VRAM

**Comment by ErikKaum** [comment]
Hi @freegheist 👋 

Sorry for being unclear, so the PR was about prefix caching but we still need the prefix chunking in. We've had some issues with it so it's been a back and forth.

Can't promise when it's in but we're working hard to get it out 🤞

**Comment by imran3180** [comment]
Same issue. Commenting for increasing the priority.

**Comment by osmalpkoras** [comment]
Same issue here.

**Comment by giladd123** [comment]
Same issue.

**Comment by cancelself** [comment]
> I can't fit this model with 128K as well, something is not playing nice here. (tested the vLLM with 128K, no problem)

next stop, vllm!

**Comment by imran3180** [comment]
@ErikKaum @drbh @Narsil Since many people are running into the same problem. Is there any plan to prioritize this bug?

**Comment by nimishbongale** [comment]
Same issue!

**Comment by rishu931997** [comment]
Is there a fix planned for this? I'm still unable to increase the context length to more than 40k. Or is there a workaround to increase the context length?

**Comment by 2016bgeyer** [comment]
@ErikKaum @Narsil 

Was this issue addressed in TGI v3 or in any of the following specific MRs?:
2673 (https://github.com/huggingface/text-generation-inference/pull/2673)
2797 (https://github.com/huggingface/text-generation-inference/pull/2797/)
2808 (https://github.com/huggingface/text-generation-inference/pull/2808)

Many people are blocked by this issue and if it resolved, that would be really good to track here

**Comment by ErikKaum** [comment]
Hi @2016bgeyer 👋 

Sorry for not updating here. But I can confirm that with TGI version `3.0.1` I ran this setup and it worked:

- model: [hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4](https://huggingface.co/hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4)
- GPU: Nvidia A100, 80 GB
- TGI auto selects `Maximum total tokens defaulted to 119178`

I leave all the other fields undefined so the TGI auto selects them to max out on the hardware. So it's not fully up to the 128k context but close enough imo. And you'd get up to the 128k with more vRAM or more aggressively quantized. 

Hopefully this helps 👍

**Comment by 2016bgeyer** [comment]
Fantastic, thank you for the update!

In the future, is there any chance you guys could track and link issues in your MRs a bit more, at least when multiple people have been blocked by an issue? Thanks!

**Comment by YasminAwad** [comment]
Hi @ErikKaum 

I saw you have been able to run up to 128k context. I have tried to run TGI with llama 3.1 70B giving it:

```
MAX_TOTAL_TOKENS=139264
MAX_INPUT_TOKENS=131072
```

But I get the following:

```
Error: Backend(NotEnoughMemory(139264))
ERROR text_generation_launcher: Webserver Crashed
```

I am using 4 H100 80GB GPUs.
It works fine using:

```
MAX_TOTAL_TOKENS=2048
MAX_INPUT_TOKENS=1024
```

I will leave the docker-compose.yml and dockerfile.tgi. Do you know what I am doing wrong?
I am sorry to bother you. Thank you for your time.

docker-compose.yml:

```
services:
   
  tgi:
    container_name: yasmin_tgi_server_70B
    build:
      context: .
      dockerfile: Dockerfile.tgi
      args:
        MODEL_NAME: ${MODEL_NAME}
        HF_TOKEN: ${HF_TOKEN}
    shm_size: 1g
    image: ghcr.io/huggingface/text-generation-inference:3.1.0
    ports:
      - "${PORT}:8080"
    environment:
      - MODEL_NAME=${MODEL_NAME}
      - PORT=8080
      - DTYPE=${DTYPE}
      - NUM_SHARD=${NUM_SHARD}
      - MAX_TOTAL_TOKENS=${MAX_TOTAL_TOKENS}
      - MAX_INPUT_TOKENS=${MAX_INPUT_TOKENS}
      - MAX_BATCH_PREFILL_TOKENS=${MAX_BATCH_PREFILL_TOKENS}
      - MAX_BATCH_SIZE=${MAX_BATCH_SIZE}
      - CUDA_MEMORY_FRACTION=${CUDA_MEMORY_FRACTION}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}
    # runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
```

dockerfile.tgi:

```
# Base image from Hugging Face Text Generation Inference
FROM ghcr.io/huggingface/text-generation-inference:3.0.1

# Accept build argument
ARG MODEL_NAME
ARG HF_TOKEN
# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV MODEL_NAME=${MODEL_NAME}
ENV LOCAL_DIR="${MODEL_NAME}"
# Set the working directory to /app (absolute path)
WORKDIR /app

# Install the Hugging Face Hub client
RUN pip install huggingface-hub

# Log in to Hugging Face using an authentication token (if required)
RUN huggingface-cli login --token ${HF_TOKEN}

# Download the model to the /directory
RUN huggingface-cli download ${MODEL_NAME} --local-dir ${LOCAL_DIR}

# Expose the port for the inference server
EXPOSE ${PORT}

# Entry point to run the inference server
ENTRYPOINT ["sh", "-c"]

# Command to launch the inference server with the custom model and configurations

CMD ["text-generation-launcher --model-id ${LOCAL_DIR} \
    --port ${PORT} \
    --dtype ${DTYPE} \
    --num-shard ${NUM_SHARD} \
    --max-batch-size ${MAX_BATCH_SIZE} \
    --max-total-tokens ${MAX_TOTAL_TOKENS} \
    --max-input-tokens ${MAX_INPUT_TOKENS} \
    --max-batch-prefill-tokens ${MAX_BATCH_PREFILL_TOKENS} \
    --cuda-memory-fraction ${CUDA_MEMORY_FRACTION}"]
```
