### ISSUE TITLE
Error when launching Llama 4 Scout

### ISSUE THREAD

**Issue by ukito-pl** [huggingface/text-generation-inference#3228]
### System Info

Ubuntu 22.04.5 LTS
Docker version 27.4.1, build b9d17ea
TGI version: ghcr.io/huggingface/text-generation-inference:3.3.0
Hardware: 8x GPU Nvidia L40s 48GB, Driver Version: 560.35.03, CUDA Version: 12.6 

### Information

- [x] Docker
- [ ] The CLI directly

### Tasks

- [x] An officially supported command
- [ ] My own modifications

### Reproduction

1. Set env variables;
  - HUGGINGFACE_CACHE_PATH - path to hugging face cache folder
  - HUGGINGFACE_TOKEN - token with permissions to download [llama 4 scout model](https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct)
2. Run tgi with docker compose:
````
services:
  tgi-test:
    container_name: tgi-test
    image: ghcr.io/huggingface/text-generation-inference:3.3.0
    restart: no
    deploy:
      resources:
        limits:
          cpus: '12'
          memory: 64G
        reservations:
          cpus: '8'
          memory: 32G
          devices:
          - driver: nvidia
            count: all
            capabilities:
              - gpu
    shm_size: '64gb'
    ports:
      - 80:80
    volumes:
      - ${HUGGINGFACE_CACHE_PATH}:/data
    environment:
      - MODEL_ID=meta-llama/Llama-4-Scout-17B-16E-Instruct
      - SHARDED=true
      - NUM_SHARD=8
      - CUDA_MEMORY_FRACTION=1.0
      - HF_TOKEN=${HUGGINGFACE_TOKEN}
      - LOG_LEVEL=debug
````

### Expected behavior

Service should correctly startup.

Instead I get error during warmup:
`TypeError: TransformersFlashVlmCausalLM._model_forward() got an unexpected keyword argument 'attention_mask'
2025-05-14T13:13:36.434698Z ERROR warmup{max_input_length=None max_prefill_tokens=4096 max_total_tokens=None max_batch_size=None}:warmup: text_generation_router_v3::client: backends/v3/src/client/mod.rs:45: Server error: TransformersFlashVlmCausalLM._model_forward() got an unexpected keyword argument 'attention_mask'`

Here are full logs from container:
[tgi_logs.txt](https://github.com/user-attachments/files/20224450/tgi_logs.txt)
