### ISSUE TITLE
Unable to serve tiiuae/falcon-40b-instruct on EKS G5 nodes

### ISSUE THREAD

**Issue by kush-work** [huggingface/text-generation-inference#405]
### System Info

- Platform: EKS
- Hardware: g5.12xl, 4xGPU(24Gi Each), AWS
- Deployment on EKS
- Image used:  ghcr.io/huggingface/text-generation-inference:0.8
- args passed to containers:
```
    args:
      - --num_shard
      - 4
      - --model-id
      - tiiuae/falcon-40b-instruct
      - --quantize
      - bitsandbytes
      - --trust-remote-code
      - --disable-custom-kernels
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

We are deploying the text-inference with falcon model on EKS g5.12xl nodes, this is our config values for the deployment.yaml 

```
  image:
    repository: ghcr.io/huggingface/text-generation-inference
    tag: "0.8"
  service:
    type: ClusterIP
    ports:
      - port: 8080
        targetPort: http
        protocol: TCP
        name: http
  replicaCount: 1
  autoscaling:
    enabled: false
  container:
    args:
      - --num_shard
      - 4
      - --model-id
      - tiiuae/falcon-40b-instruct
      - --quantize
      - bitsandbytes
      - --trust-remote-code
      - --disable-custom-kernels
    env:
      name: NCCL_SHM_DISABLE
      value: "1"
```

When we apply the yaml against the cluster,  we are seeing these errors 
```
2023-06-02T09:33:23.138473Z  INFO text_generation_launcher: Args { model_id: "tiiuae/falcon-40b-instruct", revision: None, sharded: None, num_shard: Some(4), quantize: None, trust_remote_code: true, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1000, max_total_tokens: 1512, max_batch_size: None, waiting_served_ratio: 1.2, max_batch_total_tokens: 32000, max_waiting_tokens: 20, port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: true, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, env: false }

2023-06-02T09:43:15.067779Z ERROR text_generation_launcher: Shard 0 failed to start:
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
You are using a model of type RefinedWeb to instantiate a model of type . This is not supported for all configurations of models and can yield errors.

2023-06-02T09:43:15.067808Z  INFO text_generation_launcher: Shutting down shards
2023-06-02T09:43:15.198326Z  INFO text_generation_launcher: Shard 1 terminated
2023-06-02T09:43:15.298811Z  INFO text_generation_launcher: Shard 2 terminated
2023-06-02T09:43:15.699189Z  INFO text_generation_launcher: Shard 3 terminated
Error: ShardCannotStart
```

### Expected behavior

The model should run as expected; we ran it inside the g5.12xl EC2 instance where it worked without any problem. If there is any way to get more verbose logs on to what failed, or if we are missing anything in our deployment we will be really grateful.

**Comment by OlivierDehaene** [comment]
Oh I see can you set `NUM_SHARD=1` manually? 
It seems that your eks does not limit the number of GPUs. The container picks up that they are 4 available and tries to use tensor parallelism (that's why you see 4 shards) which is not supported for falcon 7B. IDK why you don't get a nice stack trace though.

**Comment by OlivierDehaene** [comment]
Wait are you trying to serve 7b or 40b? Your deployment and logs contradict themselves.

**Comment by kush-work** [comment]
> Wait are you trying to serve 7b or 40b? Your deployment and logs contradict themselves.

Sorry, I attached the updated config file of 7b which we tried post failure from 40b. The logs are from the 40b itself & we still want to get 40b up & running.


> It seems that your eks does not limit the number of GPUs. The container picks up that they are 4 available and tries to use tensor parallelism (that's why you see 4 shards) which is not supported for falcon 7B. IDK why you don't get a nice stack trace though.

We have manually added `num_shard` as 4 while deploying 40b, as with single instance the model was quite slow.

**Comment by sam-h-bean** [comment]
Same issue as https://github.com/huggingface/text-generation-inference/issues/402

I think there is some issue in the missing model type. I am seeing this issue even with tons of resources

**Comment by kush-work** [comment]
> IDK we are serving all falcon models internally on eks without issues. What's weird is the absence of stacktrace. Can you guys try sha-83b8448?

Let me try that & report back.

**Comment by sam-h-bean** [comment]
same error but the signal is now coming back

```bash
{"timestamp":"2023-06-02T14:49:44.114230Z","level":"ERROR","fields":{"message":"Shard process was signaled to shutdown with signal 7"},"target":"text_generation_launcher"}
{"timestamp":"2023-06-02T14:49:44.212056Z","level":"ERROR","fields":{"message":"Shard 3 failed to start:\nThe argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.\nThe argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.\nYou are using a model of type RefinedWeb to instantiate a model of type . This is not supported for all configurations of models and can yield errors.\n"},"target":"text_generation_launcher"}

```

**Comment by kush-work** [comment]
```
llamadevinit 2023-06-02T14:44:08.106837Z  INFO text_generation_launcher: Args { model_id: "tiiuae/falcon-40b-instruct", revision: None, sharded: None, num_shard: Some(4), quantize: Some(Bitsandbytes), trust_remote_code: true, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1000, max_total_tokens: 1512, max_batch_size: None, waiting_served_ratio: 1.2, max_batch_total_tokens: 32000, max_waiting_tokens: 20, port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: true, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, env: false }
llamadevinit 2023-06-02T14:44:08.106869Z  INFO text_generation_launcher: Sharding model on 4 processes
llamadevinit 2023-06-02T14:44:08.106940Z  INFO text_generation_launcher: Starting download process.
llamadevinit 2023-06-02T14:44:09.694314Z  WARN download: text_generation_launcher: No safetensors weights found for model tiiuae/falcon-40b-instruct at revision None. Downloading PyTorch weights.
llamadevinit 
llamadevinit 2023-06-02T14:46:31.351903Z  INFO download: text_generation_launcher: Download file: pytorch_model-00008-of-00009.bin
llamadevinit 
llamadevinit 2023-06-02T14:47:07.727972Z  INFO download: text_generation_launcher: Downloaded /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/pytorch_model-00008-of-00009.bin in 0:00:36.
llamadevinit 
llamadevinit 2023-06-02T14:47:07.728041Z  INFO download: text_generation_launcher: Download: [8/9] -- ETA: 0:00:22.250000
llamadevinit 
llamadevinit 2023-06-02T14:47:07.728308Z  INFO download: text_generation_launcher: Download file: pytorch_model-00009-of-00009.bin
llamadevinit 
llamadevinit 2023-06-02T14:47:35.812993Z  INFO download: text_generation_launcher: Downloaded /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/pytorch_model-00009-of-00009.bin in 0:00:28.
llamadevinit 
llamadevinit 2023-06-02T14:47:35.813061Z  INFO download: text_generation_launcher: Download: [9/9] -- ETA: 0
llamadevinit 
llamadevinit 2023-06-02T14:47:35.813135Z  WARN download: text_generation_launcher: No safetensors weights found for model tiiuae/falcon-40b-instruct at revision None. Converting PyTorch weights to safetensors.
llamadevinit 
llamadevinit 2023-06-02T14:47:35.813283Z  INFO download: text_generation_launcher: Convert /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/pytorch_model-00001-of-00009.bin to /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/model-00001-of-00009.safetensors.
llamadevinit 
llamadevinit 2023-06-02T14:48:32.839792Z  INFO download: text_generation_launcher: Convert: [1/9] -- Took: 0:00:57.026310
llamadevinit 
llamadevinit 2023-06-02T14:48:32.839870Z  INFO download: text_generation_launcher: Convert /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/pytorch_model-00002-of-00009.bin to /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/model-00002-of-00009.safetensors.
llamadevinit 
llamadevinit 2023-06-02T14:49:11.493732Z  INFO download: text_generation_launcher: Convert: [2/9] -- Took: 0:00:38.653696
llamadevinit 
llamadevinit 2023-06-02T14:49:11.493798Z  INFO download: text_generation_launcher: Convert /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/pytorch_model-00003-of-00009.bin to /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/model-00003-of-00009.safetensors.
llamadevinit 
llamadevinit 2023-06-02T14:49:51.257831Z  INFO download: text_generation_launcher: Convert: [3/9] -- Took: 0:00:39.763835
llamadevinit 
llamadevinit 2023-06-02T14:49:51.257880Z  INFO download: text_generation_launcher: Convert /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/pytorch_model-00004-of-00009.bin to /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/model-00004-of-00009.safetensors.
llamadevinit 
llamadevinit 2023-06-02T14:50:30.376754Z  INFO download: text_generation_launcher: Convert: [4/9] -- Took: 0:00:39.118684
llamadevinit 
llamadevinit 2023-06-02T14:50:30.376802Z  INFO download: text_generation_launcher: Convert /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/pytorch_model-00005-of-00009.bin to /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/model-00005-of-00009.safetensors.
llamadevinit 
llamadevinit 2023-06-02T14:51:08.773329Z  INFO download: text_generation_launcher: Convert: [5/9] -- Took: 0:00:38.396316
llamadevinit 
llamadevinit 2023-06-02T14:51:08.773385Z  INFO download: text_generation_launcher: Convert /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/pytorch_model-00006-of-00009.bin to /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/model-00006-of-00009.safetensors.
llamadevinit 
llamadevinit 2023-06-02T14:51:45.487105Z  INFO download: text_generation_launcher: Convert: [6/9] -- Took: 0:00:36.713552
llamadevinit 
llamadevinit 2023-06-02T14:51:45.487202Z  INFO download: text_generation_launcher: Convert /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/pytorch_model-00007-of-00009.bin to /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/model-00007-of-00009.safetensors.
llamadevinit 
llamadevinit 2023-06-02T14:52:26.057868Z  INFO download: text_generation_launcher: Convert: [7/9] -- Took: 0:00:40.570538
llamadevinit 
llamadevinit 2023-06-02T14:52:26.057961Z  INFO download: text_generation_launcher: Convert /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/pytorch_model-00008-of-00009.bin to /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/model-00008-of-00009.safetensors.
llamadevinit 
llamadevinit 2023-06-02T14:53:06.502451Z  INFO download: text_generation_launcher: Convert: [8/9] -- Took: 0:00:40.444298
llamadevinit 
llamadevinit 2023-06-02T14:53:06.502506Z  INFO download: text_generation_launcher: Convert /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/pytorch_model-00009-of-00009.bin to /data/models--tiiuae--falcon-40b-instruct/snapshots/5b9409410d251ab8e06c48078721c8e2b71fa8a1/model-00009-of-00009.safetensors.
llamadevinit 
llamadevinit 2023-06-02T14:53:36.778150Z  INFO download: text_generation_launcher: Convert: [9/9] -- Took: 0:00:30.275418
llamadevinit 
llamadevinit 2023-06-02T14:53:37.189304Z  INFO text_generation_launcher: Successfully downloaded weights.
llamadevinit 2023-06-02T14:53:37.189341Z  WARN text_generation_launcher: `trust_remote_code` is set. Trusting that model `tiiuae/falcon-40b-instruct` do not contain malicious code.
llamadevinit 2023-06-02T14:53:37.189345Z  WARN text_generation_launcher: Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
llamadevinit 2023-06-02T14:53:37.189518Z  INFO text_generation_launcher: Starting shard 0
llamadevinit 2023-06-02T14:53:37.190163Z  INFO text_generation_launcher: Starting shard 1
llamadevinit 2023-06-02T14:53:37.190271Z  INFO text_generation_launcher: Starting shard 2
llamadevinit 2023-06-02T14:53:37.190272Z  INFO text_generation_launcher: Starting shard 3
llamadevinit 2023-06-02T14:53:47.199895Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
llamadevinit 2023-06-02T14:53:47.200030Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
llamadevinit 2023-06-02T14:53:47.200323Z  INFO text_generation_launcher: Waiting for shard 2 to be ready...
llamadevinit 2023-06-02T14:53:47.200961Z  INFO text_generation_launcher: Waiting for shard 3 to be ready...
llamadevinit 2023-06-02T14:53:57.207829Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
llamadevinit 2023-06-02T14:53:57.208315Z  INFO text_generation_launcher: Waiting for shard 2 to be ready...
llamadevinit 2023-06-02T14:53:57.208499Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
llamadevinit 2023-06-02T14:53:57.209464Z  INFO text_generation_launcher: Waiting for shard 3 to be ready...
llamadevinit 2023-06-02T14:54:07.216066Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
llamadevinit 2023-06-02T14:54:07.216354Z  INFO text_generation_launcher: Waiting for shard 2 to be ready...
llamadevinit 2023-06-02T14:54:07.216959Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
llamadevinit 2023-06-02T14:54:07.217817Z  INFO text_generation_launcher: Waiting for shard 3 to be ready...
llamadevinit 2023-06-02T14:54:09.217774Z ERROR text_generation_launcher: Shard process was signaled to shutdown with signal 7
llamadevinit 2023-06-02T14:54:09.314713Z ERROR text_generation_launcher: Shard 1 failed to start:
llamadevinit The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
llamadevinit [W socket.cpp:601] [c10d] The client socket has failed to connect to [localhost]:29500 (errno: 99 - Cannot assign requested address).
llamadevinit The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
llamadevinit You are using a model of type RefinedWeb to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
llamadevinit 
llamadevinit 2023-06-02T14:54:09.314742Z  INFO text_generation_launcher: Shutting down shards
llamadevinit 2023-06-02T14:54:09.381762Z  INFO text_generation_launcher: Shard 2 terminated
llamadevinit 2023-06-02T14:54:10.246909Z  INFO text_generation_launcher: Shard 0 terminated
llamadevinit 2023-06-02T14:54:10.347972Z  INFO text_generation_launcher: Shard 3 terminated
llamadevinit Error: ShardCannotStart
Stream closed EOF for dev-init-llm-deployment/llamadevinit-7bbb6fd549-w9rf7 (llamadevinit)
```


Here's the updated log, there are no more details expect a single line of client disconn

**Comment by OlivierDehaene** [comment]
Shared memory allocations can SIGBUS if there's not enough space in /dev/shm. I see that you are already using `NCCL_SHM_DISABLE=1` so maybe it comes from somewhere else. 

I would adivse you to mount a memory volume on /dev/shm.
See [this part ](https://github.com/huggingface/text-generation-inference#a-note-on-shared-memory-shm) of the Readme.

**Comment by OlivierDehaene** [comment]
For example:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgi-falcon-40b
spec:
  replicas: 1
  selector:
    matchLabels:
      framework: tgi
      app: tgi-falcon-40b
  template:
    metadata:
      labels:
        framework: tgi
        app: tgi-falcon-40b
    spec:
      containers:
        - env:
            - name: MODEL_ID
              value: tiiuae/falcon-40b-instruct
            - name: NUM_SHARD
              value: "4"
            - name: QUANTIZE
              value: bitsandbytes
          image: registry.internal.huggingface.tech/api-inference/community/text-generation-inference:0.8.2
          name: tgi-container
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              nvidia.com/gpu: "4"
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
      volumes:
        - emptyDir:
            medium: Memory
            sizeLimit: 1Gi
          name: shm
```

**Comment by sam-h-bean** [comment]
So you don't need to set an env var to pass in the shm-size arg? I was doing something like 

```yaml
          env:
            - name: MODEL_ID
              value: "tiiuae/falcon-40b-instruct"
            - name: NUM_SHARD
              value: "4"
            - name: QUANTIZE
              value: "bitsandbytes"
            - name: PORT
              value: "6018"
            - name: TRUST_REMOTE_CODE
              value: "true"
            - name: NUM_GPUS
              value: "4"
            - name: SHM_SIZE
              value: "2g"
```

It seems I can remove the trust, shm, and num gpu env vars though.

However it worked! Thank you so much!
