### ISSUE TITLE
OpenLLama Orca mini model Expected (head_size % 8 == 0) && (head_size <= 128) to be true

### ISSUE THREAD

**Issue by llmlover** [huggingface/text-generation-inference#527]
### System Info

docker image: ghcr.io/huggingface/text-generation-inference:0.8

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Hi, thank you for the repo.
Regarding the new orca mini model (`psmathur/orca_mini_3b`)
When using an OpenLLama 3B model, I get this error for a normal and for a streaming request:
```
{"error":"Request failed during generation: Server error: Expected (head_size % 8 == 0) && (head_size <= 128) to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)","error_type":"generation"}
```

Thank you for hopefully assessing the bug.

### Expected behavior

TGI should output a generation for the 3B model.

**Comment by Narsil** [comment]
This model has `head_size == 100` which is indeed not % 8 which cannot work with flash_attention.

Try disabling flash attention.

**Comment by Narsil** [comment]
Closing as this should be the issue, feel free to comment if not. Thanks for the report !

**Comment by llmlover** [comment]
@Narsil 
Thank you for the answer! Is there a way to pad the head size to use flash_attention for faster inference?

**Comment by llmlover** [comment]
@Narsil 
Please reopen, disabling Flash Attention did not work:

```yml
version: '3.8'

services:
  text-generation-inference:
    environment:
      - USE_FLASH_ATTENTION=false
    image: ghcr.io/huggingface/text-generation-inference:0.8
    command: --model-id "psmathur/orca_mini_3b" --num-shard 1 --trust-remote-code
    volumes:
      - ./data:/data
    ports:
      - 8080:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: '1g'
```

Still results in:
```
infer:send_error: text_generation_router::infer: router/src/infer.rs:533: Request failed during generation: Server error: Expected (head_size % 8 == 0) && (head_size <= 128) to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
^CGracefully stopping... (press Ctrl+C again to force)
```
