### ISSUE TITLE
Unable to download docker

### ISSUE THREAD

**Issue by nikogamulin** [huggingface/text-generation-inference#815]
Hi,

I have been trying to download docker images for days but haven't managed to get it.

The following is the command I run:

```
model=tiiuae/falcon-7b-instruct
volume=$PWD/data # share a volume with the Docker container to avoid downloading weights every run

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.0 --model-id $model --quantize bitsandbytes
```

Then, every time, it gets stuck downloading files:

```
2023-08-11T06:39:32.403296Z  INFO text_generation_launcher: Args { model_id: "tiiuae/falcon-7b-instruct", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: Some(Bitsandbytes), dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "d0ad604a64f6", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-08-11T06:39:32.403419Z  INFO download: text_generation_launcher: Starting download process.
2023-08-11T06:39:35.992734Z  WARN text_generation_launcher: No safetensors weights found for model tiiuae/falcon-7b-instruct at revision None. Downloading PyTorch weights.

2023-08-11T06:39:36.139752Z  INFO text_generation_launcher: Download file: pytorch_model-00001-of-00002.bin
```

In the data folder, files version.txt, tmpv6g3in3e (or similar) and models--tiiuae--falcon-7b-instruct are created. The size of file tmpv6g3in3e grows for some time and then it stops.

Does anyone know how to overcome this issue?

**Comment by ai792** [comment]
Use a different approach. Download the model you need first and mount its volume during runtime.

Download docker image of the server
```
docker pull ghcr.io/huggingface/text-generation-inference:latest
````
Then download a model:
```
git clone --progress https://huggingface.co/upstage/Llama-2-70b-instruct-v2
```
Then mount it during runtime, via docker compose for example:
```
#Huggingface Inference
version: '3.5'

services:
  huggingface-inference:
    container_name: huggingface-inference
    image: ghcr.io/huggingface/text-generation-inference:latest
    shm_size: 8g
    runtime: nvidia
    volumes:
      - /data/poc-projects/models/:/data
    ports:
      - "8000:80"
    environment:
      - NVIDIA_VISIBLE_DEVICES=0,1
      - CUDA_LAUNCH_BLOCKING=1
      - MODEL_ID=/data/falcon-40b-instruct
      - SHARDED=true
      - QUANTIZE=bitsandbytes

Then:
```
echo "Drink beer"
```
:beers:

**Comment by Narsil** [comment]
Try using `-e HF_HUB_ENABLE_HF_TRANSFER=1` to see the model downloading progress.

Seems there's something wrong with the network, some environments require `--net=host`.

**Comment by nikogamulin** [comment]
> Use a different approach. Download the model you need first and mount its volume during runtime.
> 
> Download docker image of the server
> 
> ```
> docker pull ghcr.io/huggingface/text-generation-inference:latest
> ```
> 
> Then download a model:
> 
> ```
> git clone --progress https://huggingface.co/upstage/Llama-2-70b-instruct-v2
> ```
> 
> Then mount it during runtime, via docker compose for example:
> 
> ```
> #Huggingface Inference
> version: '3.5'
> 
> services:
>   huggingface-inference:
>     container_name: huggingface-inference
>     image: ghcr.io/huggingface/text-generation-inference:latest
>     shm_size: 8g
>     runtime: nvidia
>     volumes:
>       - ./models/:/data
>     ports:
>       - "8000:80"
>     environment:
>       - NVIDIA_VISIBLE_DEVICES=0,1
>       - CUDA_LAUNCH_BLOCKING=1
>       - MODEL_ID=/data/Llama-2-70b-instruct-v2
>       - SHARDED=true
>       - QUANTIZE=bitsandbytes
> ```
> 
> Then:
> 
> ```
> echo "Drink beer"
> ```
> 
> beers

Where to clone the repo?
When I run docker-compose up, the download progress starts the same way as in the case of running docker run...

The following is the modified yaml file:
```
#Huggingface Inference
version: '3.5'

services:
  huggingface-inference:
    container_name: huggingface-inference
    image: ghcr.io/huggingface/text-generation-inference:latest
    shm_size: 8g
    runtime: nvidia
    # network_mode: host # This line adds the equivalent of --net=host
    volumes:
      - ./models/:/data
    ports:
      - "8000:80"
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - CUDA_LAUNCH_BLOCKING=1
      - MODEL_ID=meta-llama/Llama-2-7b-chat-hf
      - QUANTIZE=bitsandbytes
      - HUGGING_FACE_HUB_TOKEN=hf_xxxxxxxxxxxxxxxxxxxxx
      - HF_HUB_ENABLE_HF_TRANSFER=1
```

Upon running docker-compose up, the folder ~myproject/models/models--meta-llama--Llama-2-7b-chat-hf is created along the files ~myproject/models/tmpxoy1qxe5, ~myproject/models/version.txt. I tried to put the cloned repository inside folder ~myproject/models/ but the download nevertheless commenced. I tried to rename the folder of cloned repo to models--meta-llama--Llama-2-7b-chat-hf and it also didn't prevent the download.
